### ISSUE TITLE
Episode 1 Outline - Responsive Images

### ISSUE THREAD

**Issue by tevko** [charlespeters/viewsourc.es#10]
[INTRO]

- Charles introduces topic, asks panel for experience in dealing with said subject

- Tim explains struggle to understand + RICG responsive images plugin and namedrops / humblebrags

- Brad explains photography client and how that was the perfect use case for an all encompassing responsive images solution

[QUESTIONS]

- why not just use javascript?
- why not just use css?
- what about bandwidth?

**Comment by tevko** [comment]
that's what I have so far as an outline, please feel free to add / edit as needed!

**Comment by charlespeters** [comment]
were we going to have a guest?
