### ISSUE TITLE
Episode 0 - outline

### ISSUE THREAD

**Issue by tevko** [charlespeters/viewsourc.es#12]

**Comment by charlespeters** [comment]
- intro music 
- hey there xyz
- round-table introductions
- what we're discussing today
```
if($guest == true ) {
   $guest.introduce();
} else {
   // keep moving
}
```
- topic specific rhetoric 
- where to find each other online / plugs
- goodbye
- closing music

**Comment by tevko** [comment]
i can do the intro

**Comment by charlespeters** [comment]
the intro music?

**Comment by tevko** [comment]
no the voice intro
