### ISSUE TITLE
Intro Music

### ISSUE THREAD

**Issue by charlespeters** [charlespeters/viewsourc.es#4]
_From @charlespeters on September 27, 2014 18:34_

something electronic
something not annoying
something public domain

_Copied from original issue: charlespeters/viewsource#7_

**Comment by charlespeters** [comment]
- ['let's be friends, if that's okay' by celadon city](http://noisetrade.com/celadoncity/excursions)
- ['reproof (instrumental)' by halfnoise](http://noisetrade.com/halfnoise/halfnoise)
- ['drive vs. fly' by color therapy](http://noisetrade.com/colortherapy/introducing-color-therapy)

my vote is for the last one.

**Comment by charlespeters** [comment]
_From @tevko on September 28, 2014 6:20_

2 things. One, this website is awesome, thanks for introducing me to it.
Two, let's be friends is my favorite and definitely intro material

On Sat, Sep 27, 2014 at 6:51 PM, charles peters <notifications@github.com>
wrote:

>
>    - 'let's be friends, if that's okay' by celadon city
>    <http://noisetrade.com/celadoncity/excursions>
>    - 'reproof (instrumental)' by halfnoise
>    <http://noisetrade.com/halfnoise/halfnoise>
>    - 'drive vs. fly' by color therapy
>    <http://noisetrade.com/colortherapy/introducing-color-therapy>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/charlespeters/viewsource/issues/7#issuecomment-57068404>
> .
>



-- 

Tim Evko

//timevko.com

**Comment by charlespeters** [comment]
noisetrade is a great resource, full of great music. this isn't open source, i'll contact the artist and get permission.

**Comment by tevko** [comment]
so where we last left off on this was that we don't have permission to use 'let's be friends, if that's okay' by celadon city http://noisetrade.com/celadoncity/excursions. So we need to come up with something different. We also need an intro script. I took the liberty of coming up with one. Let me know what you think.

>Hey what's up everybody this is ViewSources where we talk all about front end web development, web design, and all of the ideas and issues surrounding the industry. My name is Tim Evko and with me is Charles Peters (says hello) and [other panelists, same format]. [SPONSER MESSAGE] Today we're gonna talk all about [EPISODE TOPIC] So thanks for tuning in and lets get started [PLAY INTRO MUSIC]
