### ISSUE TITLE
Tech Stack

### ISSUE THREAD

**Issue by charlespeters** [charlespeters/viewsourc.es#8]
_From @charlespeters on September 26, 2014 20:43_

i know you're a fan of angular and i love jekyll. i just used an angular library for audio elements from soundcloud called plangular. works so simply.

jekyll spits out an rss feed and i think you can string together podcast feed from soundcloud and you can host stuff just on github pages. thoughts?

_Copied from original issue: charlespeters/viewsource#3_

**Comment by charlespeters** [comment]
_From @tevko on September 26, 2014 20:45_

Sounds like a great strategy, with one exception. Sound needs to be edited

**Comment by charlespeters** [comment]
i mean you uploaded edited episodes to soundcloud

**Comment by charlespeters** [comment]
_From @tevko on September 26, 2014 20:48_

yes but how will we take care of sound editing?

**Comment by charlespeters** [comment]
i am open to suggestions

**Comment by charlespeters** [comment]
going to use flexbox but i'm going to use autoprefixer. cool?

**Comment by charlespeters** [comment]
_From @tevko on October 7, 2014 1:3_

I think thats more than ok, considering our audience

On Mon, Oct 6, 2014 at 4:20 PM, charles peters <notifications@github.com>
wrote:

> going to use flexbox but i'm going to use autoprefixer. cool?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/charlespeters/viewsource/issues/3#issuecomment-58089767>
> .
>



-- 

Tim Evko

//timevko.com

**Comment by tevko** [comment]
I don't think we need Angular for the site. Let me look into the soundcloud api to see if we can create the feed from scratch

**Comment by charlespeters** [comment]
if you wanna ditch soundcloud altogether that's also fine. just want to be able to really style the player like the [plangular](https://github.com/jxnblk/plangular) library.
